package com.tts.subscriberlist.subscriber;

import org.hibernate.annotations.CreationTimestamp;

import javax.persistence.*;
import java.util.Date;

// @Entity designates a plain old Java object (POJO) class as entity
// so that we can use it with JPA services
@Entity
public class Subscriber {
    //@Id sets the 'id' as the primary key
    @Id

    // @GeneratedValue allows the id to be generated by the underlying database
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    private String firstName;
    private String lastName;
    private String userName;

    //@Column attribute is stored in a database table column whose name
    // matches that of the persistent field or property
    // @CreationTimeStamp allows the date to be generated by the system
    @Column
    @CreationTimestamp
    private Date signedUp;

    public Subscriber(String firstName, String lastName, String userName, Date signedUp){
        this.firstName = firstName;
        this.lastName = lastName;
        this.userName = userName;
        this.signedUp = signedUp;
    }

    public Subscriber() {
        // non-argument constructor needed for JPA
    }

    @Override
    public String toString() {
        return "Subscriber{" +
                "id=" + id +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", userName='" + userName + '\'' +
                ", signedUp=" + signedUp +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public Date getSignedUp() {
        return signedUp;
    }

    public void setSignedUp(Date signedUp) {
        this.signedUp = signedUp;
    }




}
